# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orchestrator_pb2 as orchestrator__pb2


class start_orchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.executePipeline = channel.unary_unary(
                '/start_orchestrator/executePipeline',
                request_serializer=orchestrator__pb2.PipelineConfig.SerializeToString,
                response_deserializer=orchestrator__pb2.PipelineStatus.FromString,
                )


class start_orchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def executePipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_start_orchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'executePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.executePipeline,
                    request_deserializer=orchestrator__pb2.PipelineConfig.FromString,
                    response_serializer=orchestrator__pb2.PipelineStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'start_orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class start_orchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def executePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/start_orchestrator/executePipeline',
            orchestrator__pb2.PipelineConfig.SerializeToString,
            orchestrator__pb2.PipelineStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
