# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orchestrator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orchestrator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12orchestrator.proto\"J\n\x0ePipelineConfig\x12\x11\n\tblueprint\x18\x01 \x01(\t\x12\x12\n\ndockerinfo\x18\x02 \x01(\t\x12\x11\n\tprotoszip\x18\x03 \x01(\x0c\"8\n\x0ePipelineStatus\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x12\n\nstatusText\x18\x02 \x01(\t2I\n\x12start_orchestrator\x12\x33\n\x0f\x65xecutePipeline\x12\x0f.PipelineConfig\x1a\x0f.PipelineStatusb\x06proto3'
)




_PIPELINECONFIG = _descriptor.Descriptor(
  name='PipelineConfig',
  full_name='PipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blueprint', full_name='PipelineConfig.blueprint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dockerinfo', full_name='PipelineConfig.dockerinfo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protoszip', full_name='PipelineConfig.protoszip', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=96,
)


_PIPELINESTATUS = _descriptor.Descriptor(
  name='PipelineStatus',
  full_name='PipelineStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='PipelineStatus.statusCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='statusText', full_name='PipelineStatus.statusText', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['PipelineConfig'] = _PIPELINECONFIG
DESCRIPTOR.message_types_by_name['PipelineStatus'] = _PIPELINESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PipelineConfig = _reflection.GeneratedProtocolMessageType('PipelineConfig', (_message.Message,), {
  'DESCRIPTOR' : _PIPELINECONFIG,
  '__module__' : 'orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:PipelineConfig)
  })
_sym_db.RegisterMessage(PipelineConfig)

PipelineStatus = _reflection.GeneratedProtocolMessageType('PipelineStatus', (_message.Message,), {
  'DESCRIPTOR' : _PIPELINESTATUS,
  '__module__' : 'orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:PipelineStatus)
  })
_sym_db.RegisterMessage(PipelineStatus)



_START_ORCHESTRATOR = _descriptor.ServiceDescriptor(
  name='start_orchestrator',
  full_name='start_orchestrator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=156,
  serialized_end=229,
  methods=[
  _descriptor.MethodDescriptor(
    name='executePipeline',
    full_name='start_orchestrator.executePipeline',
    index=0,
    containing_service=None,
    input_type=_PIPELINECONFIG,
    output_type=_PIPELINESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_START_ORCHESTRATOR)

DESCRIPTOR.services_by_name['start_orchestrator'] = _START_ORCHESTRATOR

# @@protoc_insertion_point(module_scope)
